### ISSUE TITLE
Missing User Guide on wiki

### ISSUE THREAD

**Issue by neoJINXD** [neoJINXD/Eternity#18]
The User Guide section of the wiki on GitHub is empty, We need to fill that out with the proper information.

**Comment by cpotteck** [comment]
As discussed on June 3rd, this does not seem to be a requirement for the project, but can still be valuable to create and maintain.

One idea is to list possible errors and error messages and detail possible causes/fixes. This could satisfy the prof's suggestion that error messages should guide the user towards a valid input.

**Comment by cpotteck** [comment]
can add mention of #40
