### ISSUE TITLE
Speech input

### ISSUE THREAD

**Issue by cpotteck** [neoJINXD/Eternity#27]

**Comment by SwatiPareek** [comment]
Work is currently in "SpeechButton" branch  --although not all changes were pushed (local repo is unstable). 


Tasks I've been stuck on: 
-Need to add PyAudio whl file to requirements file -- Different operating systems and versions of Python will require different whl files (Source: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio). Currently added 32 bit for windows with python 3.8 but not sure this will work for others
-Input box needs to be updated with text as you speak but this would need me to create a python shell, run the program, update input box and clear the input box at appropriate time (i.e. after 1 min of silence) . Alternatively we can ignore putting any expressions in the input box as the user is speaking and just update the input box with the output box after a query is complete [or simply just output speech]. This would assume the feature is exclusively to be used hands-off but then the microphone would need to pause enough time between listening and responding to not confuse computer's response as user input. 
-May need to employ multi-threading for previous issue, seemed to work okay earlier but as parsing itself takes some time, perhaps this means we would need to implement a data structure like a message queue. 
-Unsure how to loop info between python and electron back and forth, shell should not die in between each step or we will need to re-calibrate. 
-Current text to speech needs to be platform independent [Need to test this]
-Access to microphone for web application, alternative is to only have speech mode for native application
-Once everything is working, may want to switch the API we use, currently using Google API which has a limit of 50 queries per day.

**Comment by neoJINXD** [comment]
Closing since deemed to be not required
