### ISSUE TITLE
Degree/Radian conversion

### ISSUE THREAD

**Issue by cpotteck** [neoJINXD/Eternity#28]

**Comment by SwatiPareek** [comment]
Thoughts: 
Calculator must save state if we want a realistic deg/radian mode. This would mean during deg mode, the result of sin(1) would be different than in radian mode. Similar reasoning for other trigonometric functions. 

Alternatively we can chose to design a function that the user must specifically press to convert their answer into radians. This is perhaps easier to program but more difficult for users.

**Comment by SwatiPareek** [comment]
There is also a grad function in calculators. Do we want to add this as well? 
I've never used it personally but it seems as straightforward as rad/deg conversion. 

Currently making changes in deg_to_radian branch (has been pushed remotely)
- Has deg/radian functions
